import type { Cliente } from "./types"

export const clientesData: Cliente[] = [
  {
    id: "001",
    idFechaCliente: "2025-01-15",
    horaCliente: "10:30",
    nombre: "María González",
    telefono: "+34 612 345 678",
    mail: "maria.gonzalez@email.com",
    lugar: "Salón Principal - Madrid",
    cantidadPersonas: 120,
    observacion: "Cliente VIP, requiere menú especial vegetariano",
    observaciones: [
      {
        id: "obs-001-1",
        fecha: "2025-01-15 10:30",
        texto: "Cliente VIP, requiere menú especial vegetariano",
        autor: "Carlos Ruiz",
      },
      {
        id: "obs-001-2",
        fecha: "2025-01-16 14:20",
        texto: "Confirmado menú vegetariano con chef. Cliente solicita vinos orgánicos.",
        autor: "Carlos Ruiz",
      },
    ],
    redireccion: "Web corporativa",
    canal: "Email",
    respuestaViaMail: "Sí",
    asignacionComercial: "carlos.ruiz@empresa.com",
    horarioInicioEvento: "19:00",
    horarioFinalizacionEvento: "23:30",
    fechaEvento: "2025-03-20",
    sector: "Corporativo",
    vendedorComercialAsignado: "Carlos Ruiz",
    marcaTemporal: "2025-01-15 10:30:00",
    demora: "0 días",
    presupuesto: "€15,000",
    fechaPresupEnviado: "2025-01-16",
    estado: "Activo",
  },
  {
    id: "002",
    idFechaCliente: "2025-01-18",
    horaCliente: "14:15",
    nombre: "Juan Martínez",
    telefono: "+34 623 456 789",
    mail: "juan.martinez@email.com",
    lugar: "Terraza Jardín - Barcelona",
    cantidadPersonas: 80,
    observacion: "Boda al aire libre, necesita carpa de respaldo",
    observaciones: [
      {
        id: "obs-002-1",
        fecha: "2025-01-18 14:15",
        texto: "Boda al aire libre, necesita carpa de respaldo",
        autor: "Ana López",
      },
    ],
    redireccion: "Redes sociales",
    canal: "Instagram",
    respuestaViaMail: "Sí",
    asignacionComercial: "ana.lopez@empresa.com",
    horarioInicioEvento: "17:00",
    horarioFinalizacionEvento: "02:00",
    fechaEvento: "2025-06-15",
    sector: "Social",
    vendedorComercialAsignado: "Ana López",
    marcaTemporal: "2025-01-18 14:15:00",
    demora: "1 día",
    presupuesto: "€22,500",
    fechaPresupEnviado: "2025-01-19",
    estado: "Pendiente",
  },
  {
    id: "003",
    idFechaCliente: "2025-01-20",
    horaCliente: "09:00",
    nombre: "Empresa Tech Solutions S.L.",
    telefono: "+34 634 567 890",
    mail: "eventos@techsolutions.com",
    lugar: "Centro de Convenciones - Valencia",
    cantidadPersonas: 250,
    observacion: "Conferencia anual, requiere equipamiento audiovisual completo",
    observaciones: [
      {
        id: "obs-003-1",
        fecha: "2025-01-20 09:00",
        texto: "Conferencia anual, requiere equipamiento audiovisual completo",
        autor: "Pedro Sánchez",
      },
      {
        id: "obs-003-2",
        fecha: "2025-01-21 11:30",
        texto: "Cliente solicita 3 proyectores 4K y sistema de sonido profesional",
        autor: "Pedro Sánchez",
      },
      {
        id: "obs-003-3",
        fecha: "2025-01-22 16:45",
        texto: "Confirmado equipo técnico. Necesitan streaming en vivo.",
        autor: "Pedro Sánchez",
      },
    ],
    redireccion: "Referido",
    canal: "Teléfono",
    respuestaViaMail: "No",
    asignacionComercial: "pedro.sanchez@empresa.com",
    horarioInicioEvento: "09:00",
    horarioFinalizacionEvento: "18:00",
    fechaEvento: "2025-04-10",
    sector: "Corporativo",
    vendedorComercialAsignado: "Pedro Sánchez",
    marcaTemporal: "2025-01-20 09:00:00",
    demora: "0 días",
    presupuesto: "€45,000",
    fechaPresupEnviado: "2025-01-20",
    estado: "Activo",
  },
  {
    id: "004",
    idFechaCliente: "2025-01-22",
    horaCliente: "16:45",
    nombre: "Laura Fernández",
    telefono: "+34 645 678 901",
    mail: "laura.fernandez@email.com",
    lugar: "Restaurante El Mirador - Sevilla",
    cantidadPersonas: 45,
    observacion: "Cumpleaños 50, decoración elegante en dorado y negro",
    observaciones: [
      {
        id: "obs-004-1",
        fecha: "2025-01-22 16:45",
        texto: "Cumpleaños 50, decoración elegante en dorado y negro",
        autor: "María Torres",
      },
    ],
    redireccion: "Google",
    canal: "Web",
    respuestaViaMail: "Sí",
    asignacionComercial: "maria.torres@empresa.com",
    horarioInicioEvento: "20:00",
    horarioFinalizacionEvento: "01:00",
    fechaEvento: "2025-02-28",
    sector: "Social",
    vendedorComercialAsignado: "María Torres",
    marcaTemporal: "2025-01-22 16:45:00",
    demora: "2 días",
    presupuesto: "€8,500",
    fechaPresupEnviado: "2025-01-24",
    estado: "Cerrado",
  },
  {
    id: "005",
    idFechaCliente: "2025-01-25",
    horaCliente: "11:20",
    nombre: "Roberto Díaz",
    telefono: "+34 656 789 012",
    mail: "roberto.diaz@email.com",
    lugar: "Hacienda Los Olivos - Granada",
    cantidadPersonas: 150,
    observacion: "Boda tradicional, ceremonia religiosa incluida",
    observaciones: [
      {
        id: "obs-005-1",
        fecha: "2025-01-25 11:20",
        texto: "Boda tradicional, ceremonia religiosa incluida",
        autor: "Carlos Ruiz",
      },
    ],
    redireccion: "Recomendación",
    canal: "WhatsApp",
    respuestaViaMail: "Sí",
    asignacionComercial: "carlos.ruiz@empresa.com",
    horarioInicioEvento: "12:00",
    horarioFinalizacionEvento: "05:00",
    fechaEvento: "2025-09-12",
    sector: "Social",
    vendedorComercialAsignado: "Carlos Ruiz",
    marcaTemporal: "2025-01-25 11:20:00",
    demora: "0 días",
    presupuesto: "€35,000",
    fechaPresupEnviado: "2025-01-25",
    estado: "Activo",
  },
  {
    id: "006",
    idFechaCliente: "2025-01-28",
    horaCliente: "13:30",
    nombre: "Asociación Cultural Andalucía",
    telefono: "+34 667 890 123",
    mail: "info@culturaandalucia.org",
    lugar: "Teatro Municipal - Málaga",
    cantidadPersonas: 300,
    observacion: "Gala benéfica anual, necesita escenario y sonido profesional",
    observaciones: [
      {
        id: "obs-006-1",
        fecha: "2025-01-28 13:30",
        texto: "Gala benéfica anual, necesita escenario y sonido profesional",
        autor: "Ana López",
      },
    ],
    redireccion: "Email directo",
    canal: "Email",
    respuestaViaMail: "Sí",
    asignacionComercial: "ana.lopez@empresa.com",
    horarioInicioEvento: "19:30",
    horarioFinalizacionEvento: "23:00",
    fechaEvento: "2025-05-18",
    sector: "Cultural",
    vendedorComercialAsignado: "Ana López",
    marcaTemporal: "2025-01-28 13:30:00",
    demora: "3 días",
    presupuesto: "€28,000",
    fechaPresupEnviado: "2025-01-31",
    estado: "Pendiente",
  },
  {
    id: "007",
    idFechaCliente: "2025-02-01",
    horaCliente: "10:00",
    nombre: "Carmen Ruiz",
    telefono: "+34 678 901 234",
    mail: "carmen.ruiz@email.com",
    lugar: "Hotel Boutique Centro - Bilbao",
    cantidadPersonas: 60,
    observacion: "Aniversario de empresa, cóctel y cena",
    observaciones: [
      {
        id: "obs-007-1",
        fecha: "2025-02-01 10:00",
        texto: "Aniversario de empresa, cóctel y cena",
        autor: "Pedro Sánchez",
      },
    ],
    redireccion: "LinkedIn",
    canal: "LinkedIn",
    respuestaViaMail: "No",
    asignacionComercial: "pedro.sanchez@empresa.com",
    horarioInicioEvento: "19:00",
    horarioFinalizacionEvento: "00:00",
    fechaEvento: "2025-03-15",
    sector: "Corporativo",
    vendedorComercialAsignado: "Pedro Sánchez",
    marcaTemporal: "2025-02-01 10:00:00",
    demora: "1 día",
    presupuesto: "€12,000",
    fechaPresupEnviado: "2025-02-02",
    estado: "Cancelado",
  },
  {
    id: "008",
    idFechaCliente: "2025-02-03",
    horaCliente: "15:45",
    nombre: "David Moreno",
    telefono: "+34 689 012 345",
    mail: "david.moreno@email.com",
    lugar: "Finca Rural La Esperanza - Toledo",
    cantidadPersonas: 100,
    observacion: "Comunión, ambiente familiar y relajado",
    observaciones: [
      {
        id: "obs-008-1",
        fecha: "2025-02-03 15:45",
        texto: "Comunión, ambiente familiar y relajado",
        autor: "María Torres",
      },
    ],
    redireccion: "Facebook",
    canal: "Facebook",
    respuestaViaMail: "Sí",
    asignacionComercial: "maria.torres@empresa.com",
    horarioInicioEvento: "13:00",
    horarioFinalizacionEvento: "19:00",
    fechaEvento: "2025-05-25",
    sector: "Social",
    vendedorComercialAsignado: "María Torres",
    marcaTemporal: "2025-02-03 15:45:00",
    demora: "0 días",
    presupuesto: "€18,000",
    fechaPresupEnviado: "2025-02-03",
    estado: "Activo",
  },
]
